### ISSUE TITLE
model size mtric not working with HAT

### ISSUE THREAD

**Issue by Darkmyter** [scikit-multiflow/scikit-multiflow#71]
When evaluating HAT with model size metric, the evaluator crashs with error ```'int' object has no attribute 'calc_byte_size_including_subtree' ``` At the first example after n_wait.
 
Part of the problem is children missing .values().
Fixing this makes `calculate_object_size(HAT)`raise the error at `sys.getsizeof(obj)` : an interger is needed.
So the problem is in `__sizeof__()`

---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by Darkmyter** [comment]
Hoeffding tree also has a missing .values() at `subtree_depth`

**Comment by jacobmontiel** [comment]
Adding @smastelini to the discussion to investigate this further, comments/recommendations are welcomed.

**Comment by smastelini** [comment]
Hello to everyone!

I'm currently in a conference, so sadly I can't contribute too much "code-wise" today.

But some interesting points I plan to investigate ASAP:

My implementation of the object size calculation theoretically is independent of the __sizeof__ methods in the hoeffding trees. 

Being a inner python method, `__sizeof__` may be being called from `os.getsizeof`. So, this could be the source of the problem.

ASAP I will investigate how those modules are interacting.

@Darkmyter, could you provide me a reproductive example for my tests?

**Comment by jacobmontiel** [comment]
Thanks for the pointers @smastelini 

There is no rush given that 1) there is a workaround (deactivate the memory measurement) and 2) HAT is functional.

The following code will trigger the error:

```python
from skmultiflow.evaluation.evaluate_prequential import EvaluatePrequential
from skmultiflow.data.hyper_plane_generator import HyperplaneGenerator
from skmultiflow.trees.hoeffding_adaptive_tree import HAT
"""1. Create stream"""
stream = HyperplaneGenerator(mag_change=0.001, noise_percentage=0.1, random_state=2)
stream.prepare_for_use()

"""2. Create classifier"""
hat = HAT()

"""3. Setup evaluator"""
evaluator = EvaluatePrequential(show_plot=True,
                                pretrain_size=1,
                                max_samples=10000,
                                metrics=['accuracy', 'kappa', 'kappa_t', 'running_time', 'model_size'])
```

I noticed that the error is triggered by the memory calculation but not on the first call, actually it works for some time and fails after 3600 samples. Maybe this is related to the learn/split nodes in HAT?

**Comment by smastelini** [comment]
Hello @jacobmontiel and @Darkmyter,

I finally came back from the conference. I performed some tests and I think I found the problem.

Initially I thought that the `calculate_object_size` function had some bug, but in fact the problem was quite simple:

https://github.com/scikit-multiflow/scikit-multiflow/blob/6103e0344f3838727c7ca1590195a90070de29d9/src/skmultiflow/trees/hoeffding_adaptive_tree.py#L153-L154

The `get_weight_estimation` method returns a float while a integer is expected to be returned in the `__sizeof__` methods. A simple cast of its return to int solves the problem. Besides, as pointed out by @Darkmyter, there are some missing `.values()` in the loops over the HT's `_children` objects.

I did not performed a pull request yet to fix this issue because I would like to call your attention to the `calc_byte_size_including_subtree` and  `__sizeof__` methods in the hoeffding_tree implementations.

I think that we could perform some changes in those methods, considering that the `calculate_object_size` in `utils/utils.py` already considers the trees' hierarchies (subtrees) when called in a root node, for instance. Maybe, the recursive callings made by the hoeffding trees to get the subtrees sizes (`calc_byte_size_including_subtree`) could be changed to a single `calculate_object_size` at the upper levels.

Even if the current structure is maintained, in some cases, for example

https://github.com/scikit-multiflow/scikit-multiflow/blob/6103e0344f3838727c7ca1590195a90070de29d9/src/skmultiflow/trees/hoeffding_tree.py#L236

only the pointers to the class distribution statistics are being considered, not the actual stored values, as pointed out in #56. The solution would be changing the `sys.getsizeof(self._observed_class_distribution) ` to `calculate_object_size(self._observed_class_distribution, 'byte')`.

What do you think?

**Comment by jacobmontiel** [comment]
I like the idea @smastelini. It would be nice if we can streamline they size calculation.

Just wanted to point out that this will also impact the memory tracker:

https://github.com/scikit-multiflow/scikit-multiflow/blob/6103e0344f3838727c7ca1590195a90070de29d9/src/skmultiflow/trees/hoeffding_tree.py#L1341

We should use `__sizeof()__` direclty, instead of `measure_byte_size()`
