### ISSUE TITLE
Output_file should keep open during evaluation

### ISSUE THREAD

**Issue by Sun-Yuting** [scikit-multiflow/scikit-multiflow#79]
### Expected behaviour
In my work, I need the metrics output for every sample in the data stream. It means `batch_size=1` and `n_wait=1`. It still not fast enough even I turned of the plotting. It would be much faster if the output_file keeps open in the whole evaluation process.
### Actual behaviour
The `_update_file()` function opens and closes the output_file every time it was called. In my computer, it takes about 0.01s which really slows down the evaluation. Imagine I have 1 million samples to process.
### Steps to reproduce the behaviour
I used both `cProfile` module and `time.time()` to measure the time.

---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by jacobmontiel** [comment]
I agree that this is a potential issue for a special evaluation case: `batch_size=1, n_wait=1`

Instead of keeping the file open during the evaluation we could opt for a buffer approach: wait until `n` lines have been stored and then flush them into the file.

Additionally, we could control the buffer size depending on the evaluation configuration (`batch_size`, `n_wait`).

**Comment by jacobmontiel** [comment]
This is what I mean:

```python
t0=time.time()
chunk="a"*10**7
open("bla.txt", "w").write(chunk)
print("Time: {} s.".format(time.time() - t0))
```

Reference: https://stackoverflow.com/questions/27384093/fastest-way-to-write-huge-data-in-file

**Comment by Sun-Yuting** [comment]
Thanks @jacobmontiel .
The batch approach is indeed better than keep files open.
I am wondering if the asyncio module helps. Don't know much about async programming.

By the way, I've noticed that if the output need to keep at a strict `n_wait` rhythm, not only `n_wait` but also `batch_size` should be considered. It better to keep `n_wait % batch_size == 0`. Am I understand this right?

**Comment by jacobmontiel** [comment]
Hello @Sun-Yuting , here are some comments

>  (However MOA seems to keep the file open and write for every sample.)

As long as the buffer size (numer of lines) is big enough (e.g. 100K) we shouldn't have issues regarding open-close operations. 

> detach `_update_outputs()` from `_update_metrics()`

I rather not since we are handling both the file and the visualizer. But we could break `_update_file` into two parts: `_update_file_buffer()`, `_flush_file_buffer()`. In this case the latter will be called under different conditions. We need to be careful since there will be cases when the buffer might not be full yet but we want to force the flush operation (for example when the time limit is reached).

> It's more simple to use a `buffer_size` instead of `n_wait`.

Agree, thie buffer size is not related to `n_wait` nor `batch_size`

> I'm still a little confused with the meaning of `n_wait`.

`n_wait` defines the number of samples between performance measurements. `batch_size` is the number of samples to get from the stream on each iteration. It is assumed that `n_wait` >= `batch_size` but is not currently being enforced (exception handling). If `n_wait` = 1 then `batch_size` = 1, otherwise the performance measurements will be taken at wrong intervals.

Let me know if this is clear.

**Comment by jacobmontiel** [comment]
I tested two approaches:

**Option 1** Use a big buffer to reduce the number of flush operations while keeping the file open during the whole evaluation. This aims to perform a small number of flush operations (depending on the configuration of the evaluation).

**Option 2** Use a buffer smaller than the system's default buffer size. On each flush operation proceeding as open-write-close. This approach produces more flush operations, yet way less than the original approach.

For testing I used the Agrawal generator and HoeffdingTree, testing on 100K samples with `n_wait=1`.

Here are the results:

- No file writing, to measure the evaluation time used as reference (model training and testing)
```
57.9 s ± 255 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

- Current approach writing one result at a time
```
1min 10s ± 3.35 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

- Option 1  (22 flush operations)
```
1min 4s ± 6.61 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

- Option 2 (1110 flush operations)
```
1min ± 1.39 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Based on  these results, **Option 2** is an reasonable efficient way to create the results file. Additionally, by closing the file on each flush operation we reduce the risk of having a corrupted file in case something goes wrong in the middle of the evaluaiton. Finally, by using the system's default buffer time we avoid trying to figure out a compromise based on the evaluation's configuration.

I will upload the change corresponding to **Option 2**. This change affects both `EvaluatePrequential` and `EvaluateHoldout`. However the change only has impact on performance when requesting to write the evaluation results into a file, especially when `n_wait` is small.
